spring:
  application:
    name: chat-backend
  datasource:
    url: ENC(07JBQ8UstlavoxpZJxfpA3BYFOjroDe0loGOrm9TsV0NeGtlweqOV7cQz9BaedGLKtWXAYYATmziA2yYlpzL3A==)
    username: ENC(bxWQK6EA4PWwBBxCMrLExYGwb/PC1vOw)
    password: ENC(3wrG4+mPar/lM05X24NoB+FVBVwC9t5wabC1Qdj/FZg=)
    driver-class-name: org.postgresql.Driver
  # redis configuration
  data:
    redis:
      database: 0
      host: ENC(4YbaQDW2nC+iaJklNG/DcwjQ3FZHk0Uf2hD9Rygd9HM=)
      port: 6379
      password: ENC(3wrG4+mPar/lM05X24NoB+FVBVwC9t5wabC1Qdj/FZg=)
      timeout: 10000

# mybatis mapper xml
mybatis-flex:
  mapper-locations: classpath*:/mapper/**/*.xml

# 加密，解密配置
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndTripleDES
    property:
      prefix: ENC(
      suffix: )

logging:
  level:
    org:
      springframework:
        security=TRACE: TRACE